### ISSUE TITLE
core: frontend: Getting backend offline messages while doing updates or anything a bit more heavy

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#691]
![image](https://user-images.githubusercontent.com/1215497/144069751-2bf6b769-e415-4906-bebb-a9717c088499.png)

**Comment by patrickelectric** [comment]
Possible fixed by #1037

**Comment by rafaellehmkuhl** [comment]
> Probably fixed by #1037

Because the services will be unavailable, and we will be on the Nginx `/status` case?

**Comment by rafaellehmkuhl** [comment]
Humn, ok. You're probably right.
The problem it doesn't solve is the case where there's a version update happening, right?

**Comment by patrickelectric** [comment]
Nops.

**Comment by patrickelectric** [comment]
I believe that there is no way around if the system stop answering when dealing with high load.
We may want to increase the timeout or change the behavior when loosing timestamps..

**Comment by rafaellehmkuhl** [comment]
We can have a store variable for the axios-backend instance that is updated by the version-chooser saying the system is under an update. This way, we can just block all the notifications and change everything for a "Updating system" notification.
